/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;


import dao.OceanosDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme.vcmoz
 */
public class Oceanos extends javax.swing.JFrame {

    /**
     * Creates new form Gerenciar
     */
    public Oceanos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeOC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIDOC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProfOC = new javax.swing.JTextField();
        txtAreaOC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btCriar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEncontrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPesquisaNome = new javax.swing.JTextField();
        btRelatorio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        btMenu = new javax.swing.JMenuItem();
        jOceanos = new javax.swing.JMenu();
        jEstoque = new javax.swing.JMenu();
        jConservacao = new javax.swing.JMenu();
        jPoluicao = new javax.swing.JMenu();
        jRecursos = new javax.swing.JMenu();
        jAjuda = new javax.swing.JMenu();
        jQuemSomos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nome:");

        txtNomeOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeOCActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel4.setText("Profundidade:");

        jLabel3.setText("Área:");

        btCriar.setText("Criar");
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Alterar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEncontrar.setText("Encontrar");
        btEncontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncontrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Pesquisa por Nome:");

        btRelatorio.setText("Relatório");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btCriar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAtualizar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIDOC, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(btExcluir)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeOC, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAreaOC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProfOC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btEncontrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRelatorio)
                        .addGap(93, 93, 93))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtProfOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAreaOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCriar)
                    .addComponent(btAtualizar)
                    .addComponent(btExcluir))
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEncontrar)
                    .addComponent(btRelatorio))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);

        jMenu.setBackground(new java.awt.Color(0, 0, 0));
        jMenu.setText("Menu");

        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        jMenu.add(btMenu);

        jMenuBar1.add(jMenu);

        jOceanos.setText("Oceanos");
        jMenuBar1.add(jOceanos);

        jEstoque.setText("Especies");
        jMenuBar1.add(jEstoque);

        jConservacao.setText("Conservação");
        jMenuBar1.add(jConservacao);

        jPoluicao.setText("Poluição");
        jMenuBar1.add(jPoluicao);

        jRecursos.setText("Recursos");
        jMenuBar1.add(jRecursos);

        jAjuda.setText("Ajuda");
        jMenuBar1.add(jAjuda);

        jQuemSomos.setText("Quem somos");
        jMenuBar1.add(jQuemSomos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        // TODO add your handling code here:
        Principal uf = new Principal();
        uf.setVisible(true);
    }//GEN-LAST:event_btMenuActionPerformed

    private void txtNomeOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeOCActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_txtNomeOCActionPerformed

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeOC.getText();
        String area = txtAreaOC.getText();
        String profundidade = txtProfOC.getText();
        
        Oceanos o = new Oceanos();
        o.setNome(nome);
        o.setArea(area);
        o.setProfundidade(profundidade);
        
        OceanosDAO oceanosDAO = new OceanosDAO();
        OceanosDAO.inserir(o);
        
        txtNomeOC.setText("");
        txtAreaOC.setText("");
        txtProfOC.setText("");
    }//GEN-LAST:event_btCriarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
      int id = Integer.parseInt(txtIDOC.getText());
        String nome = txtNomeOC.getText();
        String area = txtAreaOC.getText();
        String profundidade = txtProfOC.getText();

        Oceanos o = new Oceanos();
        o.setId(id);
        o.setNome(nome);
        o.setArea(area);
        o.setProfundidade(profundidade);

        OceanosDAO oceanosDAO = new OceanosDAO();
        OceanosDAO.alterar(o);

        txtIDOC.setText("");
        txtNomeOC.setText("");
        txtAreaOC.setText("");
        txtProfOC.setText("");
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
       int id = Integer.parseInt(txtIDOC.getText());
        OceanosDAO oceanosDAO = new OceanosDAO();
        OceanosDAO.excluir(id);
        
        txtIDOC.setText("");
        txtNomeOC.setText("");
        txtAreaOC.setText("");
        txtProfOC.setText("");
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEncontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncontrarActionPerformed
        // TODO add your handling code here:
        int pesquisaNome = Integer.parseInt(txtPesquisaNome.getText());
        OceanosDAO oceanosDAO = new OceanosDAO();
        Oceanos o = oceanosDAO.getOceanos(pesquisaNome);
        if(o == null) {
            JOptionPane.showMessageDialog(this, "Produto não encontrado");
        } else {
            txtIDOC.setText(String.valueOf(o.getId()));
            txtNomeOC.setText(String.valueOf(o.getNome()));
            txtAreaOC.setText(String.valueOf(o.getArea()));
            txtProfOC.setText(String.valueOf(o.getProfundidade()));
        }
    }//GEN-LAST:event_btEncontrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oceanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oceanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oceanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oceanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oceanos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btEncontrar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JMenuItem btMenu;
    private javax.swing.JButton btRelatorio;
    private javax.swing.JMenu jAjuda;
    private javax.swing.JMenu jConservacao;
    private javax.swing.JMenu jEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jOceanos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jPoluicao;
    private javax.swing.JMenu jQuemSomos;
    private javax.swing.JMenu jRecursos;
    private javax.swing.JTextField txtAreaOC;
    private javax.swing.JTextField txtIDOC;
    private javax.swing.JTextField txtNomeOC;
    private javax.swing.JTextField txtPesquisaNome;
    private javax.swing.JTextField txtProfOC;
    // End of variables declaration//GEN-END:variables
}
