/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author guilherme.vcmoz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btOceanos = new javax.swing.JButton();
        btEspecies = new javax.swing.JButton();
        btAjuda = new javax.swing.JButton();
        btQuemSomos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btConservacao = new javax.swing.JButton();
        btPoluicao = new javax.swing.JButton();
        btRecursos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        btMenu = new javax.swing.JMenuItem();
        jOceanos = new javax.swing.JMenu();
        jjOceanos = new javax.swing.JMenuItem();
        jEstoque = new javax.swing.JMenu();
        jjEspecies = new javax.swing.JMenuItem();
        jConservacao = new javax.swing.JMenu();
        jjConservacao = new javax.swing.JMenuItem();
        jPoluicao = new javax.swing.JMenu();
        jjPoluicao = new javax.swing.JMenuItem();
        jRecursos = new javax.swing.JMenu();
        jjRecursos = new javax.swing.JMenuItem();
        jAjuda = new javax.swing.JMenu();
        jjAjuda = new javax.swing.JMenuItem();
        jQuemSomos = new javax.swing.JMenu();
        jjQuemSomos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Vida na Água");

        btOceanos.setBackground(new java.awt.Color(0, 0, 0));
        btOceanos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btOceanos.setForeground(new java.awt.Color(255, 255, 255));
        btOceanos.setText("Oceanos");
        btOceanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOceanosActionPerformed(evt);
            }
        });

        btEspecies.setBackground(new java.awt.Color(0, 0, 0));
        btEspecies.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEspecies.setForeground(new java.awt.Color(255, 255, 255));
        btEspecies.setText("Especies");
        btEspecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEspeciesActionPerformed(evt);
            }
        });

        btAjuda.setBackground(new java.awt.Color(0, 0, 0));
        btAjuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAjuda.setForeground(new java.awt.Color(255, 255, 255));
        btAjuda.setText("Ajuda");

        btQuemSomos.setBackground(new java.awt.Color(0, 0, 0));
        btQuemSomos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btQuemSomos.setForeground(new java.awt.Color(255, 255, 255));
        btQuemSomos.setText("Quem somos");
        btQuemSomos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuemSomosActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AA.jpg"))); // NOI18N

        btConservacao.setBackground(new java.awt.Color(0, 0, 0));
        btConservacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btConservacao.setForeground(new java.awt.Color(255, 255, 255));
        btConservacao.setText("Conservação");
        btConservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConservacaoActionPerformed(evt);
            }
        });

        btPoluicao.setBackground(new java.awt.Color(0, 0, 0));
        btPoluicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btPoluicao.setForeground(new java.awt.Color(255, 255, 255));
        btPoluicao.setText("Poluição");

        btRecursos.setBackground(new java.awt.Color(0, 0, 0));
        btRecursos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btRecursos.setForeground(new java.awt.Color(255, 255, 255));
        btRecursos.setText("Recursos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btOceanos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btConservacao)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btPoluicao, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btRecursos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btQuemSomos))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(210, 210, 210))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btOceanos)
                            .addComponent(btEspecies)
                            .addComponent(btConservacao)
                            .addComponent(btPoluicao)
                            .addComponent(btRecursos))
                        .addGap(25, 118, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAjuda)
                            .addComponent(btQuemSomos))
                        .addGap(46, 46, 46))))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);

        jMenu.setBackground(new java.awt.Color(0, 0, 0));
        jMenu.setText("Menu");

        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        jMenu.add(btMenu);

        jMenuBar1.add(jMenu);

        jOceanos.setText("Oceanos");

        jjOceanos.setText("Oceanos");
        jjOceanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjOceanosActionPerformed(evt);
            }
        });
        jOceanos.add(jjOceanos);

        jMenuBar1.add(jOceanos);

        jEstoque.setText("Especies");

        jjEspecies.setText("Especies");
        jjEspecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjEspeciesActionPerformed(evt);
            }
        });
        jEstoque.add(jjEspecies);

        jMenuBar1.add(jEstoque);

        jConservacao.setText("Conservação");

        jjConservacao.setText("Conservação");
        jjConservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjConservacaoActionPerformed(evt);
            }
        });
        jConservacao.add(jjConservacao);

        jMenuBar1.add(jConservacao);

        jPoluicao.setText("Poluição");

        jjPoluicao.setText("Poluicao");
        jPoluicao.add(jjPoluicao);

        jMenuBar1.add(jPoluicao);

        jRecursos.setText("Recursos");

        jjRecursos.setText("Recursos");
        jRecursos.add(jjRecursos);

        jMenuBar1.add(jRecursos);

        jAjuda.setText("Ajuda");

        jjAjuda.setText("Ajuda");
        jAjuda.add(jjAjuda);

        jMenuBar1.add(jAjuda);

        jQuemSomos.setText("Quem somos");

        jjQuemSomos.setText("Quem somos");
        jjQuemSomos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjQuemSomosActionPerformed(evt);
            }
        });
        jQuemSomos.add(jjQuemSomos);

        jMenuBar1.add(jQuemSomos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOceanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOceanosActionPerformed
        // TODO add your handling code here:
        Oceanos uf = new Oceanos();
        uf.setVisible(true);
    }//GEN-LAST:event_btOceanosActionPerformed

    private void btEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEspeciesActionPerformed
        // TODO add your handling code here:
        TelaEspecies uf = new TelaEspecies();
        uf.setVisible(true);
    }//GEN-LAST:event_btEspeciesActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        // TODO add your handling code here:
        Principal uf = new Principal();
        uf.setVisible(true);
    }//GEN-LAST:event_btMenuActionPerformed

    private void jjOceanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjOceanosActionPerformed
        // TODO add your handling code here:
        Oceanos uf = new Oceanos();
        uf.setVisible(true);
    }//GEN-LAST:event_jjOceanosActionPerformed

    private void jjEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjEspeciesActionPerformed
        // TODO add your handling code here:
        TelaEspecies uf = new TelaEspecies();
        uf.setVisible(true);
    }//GEN-LAST:event_jjEspeciesActionPerformed

    private void btConservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConservacaoActionPerformed
        // TODO add your handling code here:
        Conservacao uf = new Conservacao();
        uf.setVisible(true);
    }//GEN-LAST:event_btConservacaoActionPerformed

    private void jjConservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjConservacaoActionPerformed
        // TODO add your handling code here:
        Conservacao uf = new Conservacao();
        uf.setVisible(true);
    }//GEN-LAST:event_jjConservacaoActionPerformed

    private void jjQuemSomosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjQuemSomosActionPerformed
        // TODO add your handling code here:
        QuemSomos uf = new QuemSomos();
        uf.setVisible(true);
    }//GEN-LAST:event_jjQuemSomosActionPerformed

    private void btQuemSomosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuemSomosActionPerformed
        // TODO add your handling code here:
        QuemSomos uf = new QuemSomos();
        uf.setVisible(true);
    }//GEN-LAST:event_btQuemSomosActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjuda;
    private javax.swing.JButton btConservacao;
    private javax.swing.JButton btEspecies;
    private javax.swing.JMenuItem btMenu;
    private javax.swing.JButton btOceanos;
    private javax.swing.JButton btPoluicao;
    private javax.swing.JButton btQuemSomos;
    private javax.swing.JButton btRecursos;
    private javax.swing.JMenu jAjuda;
    private javax.swing.JMenu jConservacao;
    private javax.swing.JMenu jEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jOceanos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jPoluicao;
    private javax.swing.JMenu jQuemSomos;
    private javax.swing.JMenu jRecursos;
    private javax.swing.JMenuItem jjAjuda;
    private javax.swing.JMenuItem jjConservacao;
    private javax.swing.JMenuItem jjEspecies;
    private javax.swing.JMenuItem jjOceanos;
    private javax.swing.JMenuItem jjPoluicao;
    private javax.swing.JMenuItem jjQuemSomos;
    private javax.swing.JMenuItem jjRecursos;
    // End of variables declaration//GEN-END:variables
}
